# Generated by Django 4.2.11 on 2024-05-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.AutoField(db_column='cart_id', default=1, primary_key=True, serialize=False),
        ),
    ]
