# Generated by Django 4.2.11 on 2024-05-19 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='customerid',
            field=models.ForeignKey(db_column='customerId', default=1, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='base.customers'),
        ),
    ]
